// src/servicios/datosAgenciaSimulada.ts
import { AgenciaBackData } from "./transformarAgenciaBackData";

export const datosAgenciaSimuladaBack: AgenciaBackData = {
  idAgencia: 3,
  nombre: "VaGú Viajes",
  logo: "/logo.png",
  tipografia_agencia: "Verdana",
  color_tipografia_agencia: "#212121",
  color_fondo_app: "#F3F3F3",
  color_principal: "#6A0DAD",
  color_secundario: "#CBAEF0",
  color_terciario: "#3E0073",

  header_imagen_background: "/fondo-playa.jpg",
  header_imagen_background_opacidad: 0.2,
  header_video_background: "/video1.mp4",
  header_video_background_opacidad: 0.3,

  buscador_tipografia: "Verdana",
  buscador_tipografia_color: "#FFFFFF",
  buscador_tipografia_color_label: "#6A0DAD",
  buscador_inputColor: "#212121",
  buscador_inputFondoColor: "#FFFFFF",
  buscador_color_primario: "#6A0DAD",
  buscador_color_secundario: "#CBAEF0",
  buscador_color_terciario: "white",

  publicidad_existe: true,
  publicidad_titulo: "Ofertas imperdibles",
  publicidad_tipografia_color: "#6A0DAD",
  publicidad_color_primario: "#6A0DAD",
  publicidad_color_secundario: "#CBAEF0",
  publicidad_color_terciario: "#3E0073",
  publicidad_imagen_1: "paginaWeb/arboleda.jpg",
  publicidad_imagen_2: "paginaWeb/colombia.jpg",
  publicidad_imagen_3: "paginaWeb/rocas.jpg",

  tarjetas_titulo: "Destinos recomendados",
  tarjetas_tipografia: "Verdana",
  tarjetas_tipografia_color: "white",
  tarjetas_tipografia_color_titulo: "#6A0DAD",
  tarjetas_tipografia_color_contenido: "#555555",
  tarjetas_color_primario: "#6A0DAD",
  tarjetas_color_secundario: "#D6B7ED",
  tarjetas_color_terciario: "#3E0073",

  banner_registro_titulo: "Registrate y viajá con nosotros",
  banner_registro_tipografia_color: "#FFFFFF",
  banner_registro_color_primario: "#6A0DAD",
  banner_registro_color_secundario: "#CBAEF0",
  banner_registro_color_terciario: "#3E0073",

  quienes_somos_es: "En Vagu viajes, somos una agencia  dedicada a ofrecer experiencias excepcionales y memorables, adaptadas a las necesidades de cada viajero.  Nos apasiona ayudar a descubrir el mundo de manera segura, emocionante y única, con un enfoque completamente personalizado para cada cliente.\n Creemos en la importancia de combinar la calidez humana con las últimas innovaciones tecnológicas, lo que nos permite mantenernos a la vanguardia del sector y ofrecerte siempre las mejores opciones disponibles. Esta sinergia entre lo personal y lo digital es lo que nos permite garantizarte un servicio de calidad, eficiente y adaptado a tus expectativas. \n En Vagu viajes, no solo organizamos viajes, sino que creamos recuerdos inolvidables, brindándote la tranquilidad y el confort que necesitas para disfrutar de cada momento. Todo nuestro esfuerzo está dirigido a brindarte una experiencia de viaje única, que combine la excelencia en el servicio con lo último en tecnología.",
  quienes_somos_en: "We are travel experts in South America.",
  quienes_somos_pt: "Somos especialistas em viagens pela América do Sul.",

  footer_texto: "© 2025 VaGú Viajes - Todos los derechos reservados",
  footer_tipografia: "Verdana",
  footer_tipografia_color: "white",
  footer_facebook: "https://www.facebook.com/profile.php?id=61560226755026",
  footer_twitter: "",
  footer_instagram: "https://www.instagram.com/vagu_viajes_",
  footer_whatsapp: "291-4120487",
  footer_telefono: "+54 1173905607",
  footer_email: "",
  footer_direccion: "Dr. José Ramón Aguirre 3236",
  footer_ciudad: "Córdoba, Residencial Vélez Sarsfield",
  footer_pais: "Argentina",
  footer_color_primario: "#6A0DAD",
  footer_color_secundario: "#CBAEF0",
  footer_color_terciario: "#2E005A",
};
